TOWNS = [
    "ADJUNTAS",
    "AGUADA",
    "AGUADILLA",
    "AGUAS BUENAS",
    "AIBONITO",
    "ANASCO",
    "ARECIBO",
    "ARROYO",
    "BARCELONETA",
    "BARRANQUITAS",
    "BAYAMON",
    "CABO ROJO",
    "CAGUAS",
    "CAMPANILLA",
    "CAMUY",
    "CANDELARIA",
    "CANDELARIA ARENAS",
    "CANOVANAS",
    "CAROLINA",
    "CATANO",
    "CAYEY",
    "CEIBA",
    "CIALES",
    "CIDRA",
    "COAMO",
    "COCO",
    "COMERIO",
    "COROZAL",
    "CULEBRA",
    "DORADO",
    "ESTANCIAS DE FLORIDA",
    "FAJARDO",
    "FLORIDA",
    "GUANICA",
    "GUAYAMA",
    "GUAYANILLA",
    "GUAYNABO",
    "GURABO",
    "HATILLO",
    "HORMIGUEROS",
    "HUMACAO",
    "INGENIO",
    "ISABEL SEGUNDA",
    "ISABELA",
    "JAYUYA",
    "JUANA DIAZ",
    "JUNCOS",
    "LAJAS",
    "LARES",
    "LAS MARIAS",
    "LAS PIEDRAS",
    "LEVITTOWN",
    "LOIZA",
    "LUQUILLO",
    "MANATI",
    "MARICAO",
    "MAUNABO",
    "MAYAGUEZ",
    "MOCA",
    "MOROVIS",
    "NAGUABO",
    "NARANJITO",
    "OROCOVIS",
    "PAJAROS",
    "PATILLAS",
    "PENUELAS",
    "PONCE",
    "PUERTO REAL",
    "PUNTA SANTIAGO",
    "QUEBRADILLAS",
    "RINCON",
    "RIO GRANDE",
    "SABANA GRANDE",
    "SABANA SECA",
    "SALINAS",
    "SAN ANTONIO",
    "SAN GERMAN",
    "SAN ISIDRO",
    "SAN JUAN",
    "SAN LORENZO",
    "SAN SEBASTIAN",
    "SANTA BARBARA",
    "SANTA ISABEL",
    "TOA ALTA",
    "TOA BAJA",
    "TRUJILLO ALTO",
    "UTUADO",
    "VEGA ALTA",
    "VEGA BAJA",
    "VIEQUES",
    "VILLALBA",
    "YABUCOA",
    "YAUCO",
]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0",
]
