TOWNS = [
    "ADJUNTAS",
    "AGUADA",
    "AGUADILLA",
    "AGUAS BUENAS",
    "AIBONITO",
    "ANASCO",
    "ARECIBO",
    "ARROYO",
    "BARCELONETA",
    "BARRANQUITAS",
    "BAYAMON",
    "CABO ROJO",
    "CAGUAS",
    "CAMPANILLA",
    "CAMUY",
    "CANDELARIA",
    "CANDELARIA ARENAS",
    "CANOVANAS",
    "CAROLINA",
    "CATANO",
    "CAYEY",
    "CEIBA",
    "CIALES",
    "CIDRA",
    "COAMO",
    "COCO",
    "COMERIO",
    "COROZAL",
    "CULEBRA",
    "DORADO",
    "ESTANCIAS DE FLORIDA",
    "FAJARDO",
    "FLORIDA",
    "GUANICA",
    "GUAYAMA",
    "GUAYANILLA",
    "GUAYNABO",
    "GURABO",
    "HATILLO",
    "HORMIGUEROS",
    "HUMACAO",
    "INGENIO",
    "ISABEL SEGUNDA",
    "ISABELA",
    "JAYUYA",
    "JUANA DIAZ",
    "JUNCOS",
    "LAJAS",
    "LARES",
    "LAS MARIAS",
    "LAS PIEDRAS",
    "LEVITTOWN",
    "LOIZA",
    "LUQUILLO",
    "MANATI",
    "MARICAO",
    "MAUNABO",
    "MAYAGUEZ",
    "MOCA",
    "MOROVIS",
    "NAGUABO",
    "NARANJITO",
    "OROCOVIS",
    "PAJAROS",
    "PATILLAS",
    "PENUELAS",
    "PONCE",
    "PUERTO REAL",
    "PUNTA SANTIAGO",
    "QUEBRADILLAS",
    "RINCON",
    "RIO GRANDE",
    "SABANA GRANDE",
    "SABANA SECA",
    "SALINAS",
    "SAN ANTONIO",
    "SAN GERMAN",
    "SAN ISIDRO",
    "SAN JUAN",
    "SAN LORENZO",
    "SAN SEBASTIAN",
    "SANTA BARBARA",
    "SANTA ISABEL",
    "TOA ALTA",
    "TOA BAJA",
    "TRUJILLO ALTO",
    "UTUADO",
    "VEGA ALTA",
    "VEGA BAJA",
    "VIEQUES",
    "VILLALBA",
    "YABUCOA",
    "YAUCO",
]
